---
name: YAML Linting

on:
  workflow_dispatch:
    inputs:
      file:
        description: "Base name of the YAML file to lint (without .yml extension)."
        required: false
        default: ""

permissions:
  contents: read

jobs:
  lint_yaml:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install yamllint
      - name: Install yamllint
        run: |
          python3 -m pip install --user yamllint

      # Step 3: Run yamllint on Specified or All YAML Files
      - name: Lint YAML Files
        run: |
          INPUT_FILE="${{ github.event.inputs.file }}"
          if [[ -n "$INPUT_FILE" ]]; then
            TARGET_FILE=".github/workflows/$INPUT_FILE.yml"
            if [[ "$TARGET_FILE" == ".github/workflows/yamllint.yml" ]]; then
              echo "Skipping yamllint.yml as specified."
            elif [[ -f "$TARGET_FILE" ]]; then
              echo "Linting $TARGET_FILE"
              yamllint "$TARGET_FILE" || echo "Linting failed for $TARGET_FILE."
            else
              echo "Error: Specified file $TARGET_FILE does not exist."
              exit 1
            fi
          else
            echo "No specific file provided. Linting all YAML files except yamllint.yml."
            for file in .github/workflows/*.yml; do
              if [[ "$file" != ".github/workflows/yamllint.yml" ]]; then
                echo "Linting $file"
                yamllint "$file" || echo "Linting failed for $file. Moving to next file."
              else
                echo "Skipping $file"
              fi
            done
          fi

      # Step 4: Output Results
      - name: Output Results
        run: |
          echo "YAML Linting completed. Check logs for details."