---
name: Generate Core Graph
on:
  workflow_dispatch: # Allow manual trigger
    inputs:
      reason:
        description: "Reason for triggering the workflow"
        required: false
        default: "Manual trigger"

permissions:
  contents: write
  issues: write

jobs:
  core_graph_workflow:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Git configuration
      - name: Set up Git
        run: |
          git config user.name "Lyra[bot]"
          git config user.email "lyra@myshelf.ai"
          git remote set-url origin https://x-access-token:${{ secrets.MYSHELF }}@github.com/${{ github.repository }}.git

      # Step 3: Debug Directory Structure
      - name: Debug Directory Structure
        run: |
          echo "Listing directory structure:"
          find /home/runner/work/MyShelf -name "*.json"

      # Step 4: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 5: Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install networkx

      # Step 6: Validate index.json Location
      - name: Validate index.json Location
        run: |
          if [ ! -f index.json ]; then
            echo "index.json not found. Exiting." > notification-log.txt
            exit 1
          fi
          echo "index.json found at $(pwd)."

      # Step 7: Run Core Graph Generation Script
      - name: Run Core Graph Generation Script
        working-directory: /home/runner/work/MyShelf/MyShelf
        run: |
          python scripts/generate_core_graph.py || {
            echo "Core graph generation failed. Exiting." > notification-log.txt
            exit 1
          }
          echo "Core graph generation completed successfully." >> notification-log.txt

      # Step 8: Commit and Push Changes
      - name: Commit and Push Changes
        if: success()
        run: |
          echo "Staging new and updated core graph files..."
          git add snapshots/core.graph.json || echo "No new core.graph.json file to add."
          git add snapshots/core.graph.json.old || echo "No core.graph.json.old file to add."

          echo "Committing changes..."
          git commit -m "Updated core.graph.json on $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit."

          echo "Pushing changes to remote repository..."
          git push origin main || echo "No changes to push."

      # Step 9: Notify via GitHub Issues
      - name: Notify via GitHub Issues
        if: failure() # Notify only on failure
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Generate Core Graph - Workflow Failed"
          content-filepath: ./notification-log.txt
          labels: failure
        env:
          GITHUB_TOKEN: ${{ secrets.MYSHELF }}

      # Step 10: Debug Workflow State
      - name: Debug Workflow State
        run: |
          echo "Git status:"
          git status
          echo ".gitignore contents (if exists):"
          [ -f .gitignore ] && cat .gitignore || echo "No .gitignore found."
